### ISSUE TITLE
Need WC# and Day in API

### ISSUE THREAD

**Issue by hayden-t** [clapfoot/warapi#1]
The API needs someway to by code differentiate between events, so that data can be grouped by an event, and the client knows when it needs to request the static data again. it should be at highest level, eg /maps or /status

**Comment by sagitta-ignis** [comment]
Do you mean that when you request `worldconquest/maps/:mapName/static`, the response should contain an attribute like `worldConquestId ` so that you can compare it with your stored `worldConquestId` ?

You don't need such an attribute since your client should implement `ETag ` so that it knows when to request changed data between events.

However, if you wish to store static/dynamic map data for "historical" purposes, like a timeline showing how the battlefield evolved in previous world conquests, then it might make sense to have such attribute.

**Comment by hayden-t** [comment]
Thinking it would be better at the highest level, ie /maps , which does not use etags, and i feel that relying on etags either way is not safe, as it is inferred, not implicit that it correlates to a new world conquest.

**Comment by sagitta-ignis** [comment]
I agree that ETag does not correlates to a new world conquest. And yes, it will be very useful to group data by world conquest iterations. It might be needed as soon as users of the API will encounter a transition between world conquests.

I just want to clarify that 
> the client knows when it needs to request the static data again

shouldn't be related with something like a `worldConquestId` since data might not change at all between world conquests.

**Comment by hayden-t** [comment]
well the worldConquestId would change, but i think it should go in the highest level request, ie /maps . when i made the first post i hadnt thought of using etags to tell, but as replied , i would like to not have to rely on it, and have a hard number assigned from the devs. for that matter using etags would not work if the static data didnt change, between games, then there would be no indicator of WC# change...

**Comment by kcbanner** [comment]
That's a good point, in the next revision I'll include a GUID for the current World Conquest event, and perhaps an endpoint with timestamps for the different phases of the conquest.

I'll change the ETag to a hash that includes that information as well as the version within that conquest.

**Comment by hayden-t** [comment]
great

**Comment by hayden-t** [comment]
so the static etag numbers did not change as suspected, as the map did not change, so currently my ticket is valid, no way to tell, awaiting update

**Comment by hayden-t** [comment]
We recently received WC day number in the api ! Now a war unique id would be great.

**Comment by philipdiehl1** [comment]
This should all be supported now.
